title: Lost In Data
baseline: You
description: A generic blog on everything related to Data Science
baseurl: .
canonicalurl: false
theme: hyde
date:
  format: j F Y
  timezone: EST
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
